import { Button, VerticalBox, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    in property <string> results: "results";
    callback divide-income(string);

    background: #313e50;
    GridLayout {
        padding: 50px;
        spacing: 25px;
        Row {
            Text {
                text: "Enter Total Income";
                horizontal-alignment: center;
                font-size: 24px;
                font-weight: 900;
                color: white;
            }
        }

        Row {
            income := LineEdit {
                horizontal-alignment: center;
                font-size: 14px;
                placeholder-text: "Enter Total";
                height: 35px;
            }
        }

        Row {
            Button {
                text: "calculate";
                primary: true;
                height: 35px;
                clicked => {divide-income(income.text)}
            }
        }

        Row {
            VerticalBox { 
                Rectangle {
                    height: 100px;
                    background: white;
                    Text {
                        color: black;
                        font-size: 16px;
                        font-weight: 500;
                        text: root.results;
                    }
                }
            }
        }
    }
}
