[package]
name = "browser_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gfx = "0.18.3"
gfx_text = "0.33.0"
gfx_window_glutin = "0.31.0"
glutin = "0.31.3"